# Generated by Django 5.0.3 on 2024-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='course_iamges/'),
        ),
        migrations.AddField(
            model_name='course',
            name='tech_brief',
            field=models.TextField(null=True),
        ),
    ]
